dataset: text8
stage: preprocess

preprocessing:
  neg_sampling_dist_exponent: 0.75
  min_token_corpus_count: 5
  unigram_table_size: 100_000_000
  force_preprocess: false
  subsampling_threshold: 1e-5

training:
  max_neighbourhood_size: 5
  latent_dimensionality: 50
  num_negative_samples: 5
  lr_start: 0.025
  num_epochs: 1
  seed: 42
  force_train: false

eval:
  dataset: simlex999

debug:
  knn_words:
    - bad
    - good
    - peter
    - griffin
    - fire
    - music
    - one
